clean:
	rm btsoot.conf btsootdb
fullclean:
	rm -rf btsoot.conf btsootdb compare datatransfer-lib
install:
	rm -rf compare
	mkdir compare
	cd compare
	git clone git.paukra.com/paulkramme/compare.git
	cd ..
